version: '3.4'
services:
  webserver:
    image: nginx:alpine
    working_dir: /app/hana
    volumes:
      - .compose/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./hana:/app/hana
    ports:
      - 9900:80
    networks:
      - scripting

  hanadeliapp: &application
    build: .compose/php
    restart: unless-stopped
    working_dir: /app/php
    volumes:
      - ./hana:/app/php
    expose:
      - 9000
    environment:
      APP_KEY: $APP_KEY
      APP_DEBUG: $APP_DEBUG
      DB_CONNECTION: $DB_CONNECTION
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_DATABASE: $DB_DATABASE
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      CACHE_DRIVER: $CACHE_DRIVER
      QUEUE_CONNECTION: $QUEUE_CONNECTION
      REDIS_HOST: $REDIS_HOST
      REDIS_PASSWORD: $REDIS_PASSWORD
    networks:
      - scripting
      - database
      - caching

  hanadeliapp.schedule:
    <<: *application
    depends_on:
      - hanadeliapp
    entrypoint: php artisan schedule:run

  hanadeliapp.queue:
    <<: *application
    depends_on:
      - hanadeliapp
    entrypoint: php artisan queue:work --verbose

  cachedata:
    image: redis:6-alpine
    restart: unless-stopped
    expose: 
      - 6379
    networks:
      - caching

  database:
    image: postgres:alpine
    volumes:
      - .compose/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGDATA: "/var/lib/postgresql/data"
    expose:
      - 5472
    networks:
      - database

networks:
  scripting:
  database:
  caching:
