version: '3.4'
services:
  webserver:
    image: nginx:alpine
    working_dir: /app/html
    volumes:
      - .compose/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./hanadeli:/app/html
    ports:
      - 9900:80
    networks:
      - scripting

  hanadeliapp: &application
    build: .compose/php
    restart: unless-stoped
    working_dir: /app/php
    volumes:
      - ./hanadeli:/app/html
    expose:
      - 9000
    environment:
      APP_KEY: "xxx"
      APP_DEBUG: $APP_DEBUG
      DB_CONNECTION: $DB_CONNECTION
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_DATABASE: $DB_DATABASE
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      CACHE_DRIVER: $CACHE_DRIVER
      QUEUE_CONNECTION: $QUEUE_CONNECTION
      REIDS_HOST: $REIDS_HOST
    networks:
      - scripting
      - database
      - caching

  hanadeliapp.schedule:
    <<: *application
    depends_on:
      - hanadeliapp
    entrypoint: php artisan schedule:run

  hanadeliapp.queue:
    <<: *application
    depends_on:
      - hanadeliapp
    entrypoint: php artisan queue:watch --verbose

  cachedata:
    image: redis:6-alpine
    restart: unless-stopped
    expose: 
      - 6739
    networks:
      - caching

  database:
    image: postgres:alpine
    volumes:
      - .compose/postgres/data:/var/lib/postgresql/data
    expose:
      - 5472
    networks:
      - database

networks:
  scripting:
  database:
  caching:
