x-config: &appconfig
  APP_KEY: $APP_KEY
  APP_DEBUG: $APP_DEBUG
  DB_CONNECTION: $DB_CONNECTION
  DB_HOST: $DB_HOST
  DB_PORT: $DB_PORT
  DB_DATABASE: $DB_DATABASE
  DB_USERNAME: $DB_USERNAME
  DB_PASSWORD: $DB_PASSWORD
  CACHE_DRIVER: $CACHE_DRIVER
  QUEUE_CONNECTION: $QUEUE_CONNECTION
  REDIS_HOST: $REDIS_HOST
  REDIS_PASSWORD: $REDIS_PASSWORD

version: '3.4'
services:
  webserver:
    image: nginx:alpine
    working_dir: /var/www/html
    volumes:
      - .compose/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./hana:/var/www/html
    ports:
      - 9900:80
    networks:
      - scripting

  hanadeliapp: &application
    build: .compose/php
    user: ${CURRENT_UID}
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./hana:/var/www/html
      - .compose/app/storage/logs:/var/www/html/storage/logs
    expose:
      - 9000
    environment:
      <<: *appconfig
    networks:
      - scripting
      - database
      - caching

  hanadeliapp.schedule:
    <<: *application
    depends_on:
      - hanadeliapp
    entrypoint: php artisan schedule:run

  hanadeliapp.queue:
    <<: *application
    depends_on:
      - hanadeliapp
    entrypoint: php artisan queue:work --verbose

  cachedata:
    image: redis:6-alpine
    restart: unless-stopped
    expose: 
      - 6379
    networks:
      - caching

  database:
    image: postgres:alpine
    volumes:
      - .compose/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGDATA: "/var/lib/postgresql/data"
    expose:
      - 5472
    networks:
      - database

networks:
  scripting:
  database:
  caching:
